version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    container_name: backend-app
    restart: unless-stopped
    command: node server.js
    dns:
      - 8.8.8.8
      - 8.8.4.4