version: '3.8'

services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: frontend-app
    ports:
      - "3000:3000"
    restart: always