version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Volumen nur für den Frontend-Code
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev  # Startet den Vite-Dev-Server für Hot-Reload