version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    container_name: frontend-app
    command: npm run build  # Startet den Vite-Dev-Server für Hot-Reload
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
